[Settings]
ID = "4560b8f6-6216-4f55-8197-dcc125a358ef"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts. 

[build]
  # This is the directory to change to before starting a build.
  base    = "spectre/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "spectre/build/"
  # This will be your default build command
  command = "yarn build"

[[redirects]]
  from = "/TvShow/:id"
  to = "/TvShow/:id"
  force = true